version: "3"
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: docker/php/fpm
        volumes:
            - .:/var/www
        depends_on:
            - db
    php-cli:
        build:
            context: docker/php/cli
        volumes:
            - .:/var/www
        depends_on:
            - db
    db:
        build:
            context: docker/db
        ports:
            - 33061:3306
        volumes:
            - db:/var/lib/mysql
        env_file:
            - docker/db/.env
    node-cli:
        build:
            context: docker/node
        volumes:
            - .:/var/www
    redis:
        build:
            context: docker/redis
    mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"
volumes:
    db:
